package com.support.api.perf;

import io.gatling.javaapi.http.HttpProtocolBuilder;

import static io.gatling.javaapi.http.HttpDsl.http;

final class PerfConfig {

    private PerfConfig() {}

    static final String BASE_URL = System.getProperty("perf.baseUrl", "http://localhost:8080");

    static HttpProtocolBuilder httpProtocol() {
        return http
                .baseUrl(BASE_URL)
                .acceptHeader("application/json")
                .contentTypeHeader("application/json")
                .userAgentHeader("support-api-gatling");
    }

    static String createTicketBody(String customerId) {
        return """
                {
                  "customer_id": "%s",
                  "customer_email": "perf+%s@example.com",
                  "customer_name": "Perf User",
                  "subject": "Performance smoke test",
                  "description": "Generated by Gatling perf simulation - description text is long enough.",
                  "category": "other",
                  "priority": "low"
                }
                """.formatted(customerId, customerId);
    }

    static String autoClassifyBody(String customerId) {
        return """
                {
                  "customer_id": "%s",
                  "customer_email": "auto+%s@example.com",
                  "customer_name": "Auto User",
                  "subject": "Cannot login to my account",
                  "description": "I cant access my account because password is rejected. This is critical."
                }
                """.formatted(customerId, customerId);
    }
}
